// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALMIWFdjbnfjLJmqmW8vKVrdJF7toBfS0',
    appId: '1:997144137259:web:65d10b545a88145fbae46e',
    messagingSenderId: '997144137259',
    projectId: 'flutter-blog-app-675e3',
    authDomain: 'flutter-blog-app-675e3.firebaseapp.com',
    storageBucket: 'flutter-blog-app-675e3.firebasestorage.app',
    measurementId: 'G-X91732HVE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR2VWPfD4yeWCyeLZz_OMbcMnIRvcgK2M',
    appId: '1:997144137259:android:df6b0d28c2b627a0bae46e',
    messagingSenderId: '997144137259',
    projectId: 'flutter-blog-app-675e3',
    storageBucket: 'flutter-blog-app-675e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkWUKK-Y1yc9L8QDqfiiPOg_7kl4OdUl4',
    appId: '1:997144137259:ios:9bd9d63bd390b9e7bae46e',
    messagingSenderId: '997144137259',
    projectId: 'flutter-blog-app-675e3',
    storageBucket: 'flutter-blog-app-675e3.firebasestorage.app',
    iosBundleId: 'com.example.blog',
  );
}
